#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

npm run lint
npm test
if [[ $(grep -r --include \*.ts 'console.info' src | wc -l) -gt 0 ]]; then exit 1; fi
if [[ $(grep -r --include \*.ts 'test.only' tests | wc -l) -gt 0 ]]; then exit 1; fi
if [[ $(grep -r --include \*.ts 'describe.only' tests | wc -l) -gt 0 ]]; then exit 1; fi
